### ISSUE TITLE
Fails to build with clang-4.0

### ISSUE THREAD

**Issue by yurivict** [grame-cncm/faustlive#2]
```
../../src/MainStructure/FLWindow.cpp:1336:54: error: no member named 'get_sample_rate' in 'AudioManager'; did you mean 'getSampleRate'?
    fSettings->setValue("SampleRate", fAudioManager->get_sample_rate());
                                                     ^~~~~~~~~~~~~~~
                                                     getSampleRate
../../src/Audio/JA/JA_audioManager.cpp:95:28: error: no member named 'default_connections' in 'JA_audioFader'
            fCurrentAudio->default_connections();  
            ~~~~~~~~~~~~~  ^
../../src/Audio/JA/JA_audioManager.cpp:114:27: error: no member named 'get_buffer_size' in 'JA_audioFader'
    return fCurrentAudio->get_buffer_size();
           ~~~~~~~~~~~~~  ^
../../src/Audio/JA/JA_audioManager.cpp:119:27: error: no member named 'get_sample_rate' in 'JA_audioFader'
    return fCurrentAudio->get_sample_rate();
           ~~~~~~~~~~~~~  ^
../../src/Audio/JA/JA_audioFactory.cpp:29:16: error: allocating an object of abstract class type 'JA_audioManager'
    return new JA_audioManager(cb, arg);
               ^
```

**Comment by sletz** [comment]
Try to build the "dev" branch for now.

**Comment by yurivict** [comment]
"dev" branch compiles, but fails to link:
> /usr/bin/ld: cannot find -lHTTPDFaust

**Comment by sletz** [comment]
Be sur to compile HTTP stuff in faust2: 

make httpd && sudo make install

then recompile FaustLive

**Comment by yurivict** [comment]
```make httpd``` in faust doesn't build UdpSocket.cpp. faustlive build fails - can't find UdpSocket::~UdpSocket.

**Comment by sletz** [comment]
UdpSocket is actually part of osclib. Maybe rebuild/reinstall faust2 completely?

**Comment by yurivict** [comment]
> Maybe rebuild/reinstall faust2 completely?

I did, and UdpSocket isn't built at all.
UdpSocket.o is mentioned in one Makefile as a target, but this target isn't ever used, so it isn't built.

**Comment by sletz** [comment]
UdpSocket.o is mentioned in one Makefile as a target  ==> where ?

**Comment by yurivict** [comment]
In faust-2.1.0:

```
# grep -r UdpSocket.o work/
work/faust-2-1-0/architecture/osclib/oscpack/Makefile:ip/posix/UdpSocket.o: ip/UdpSocket.h ip/NetworkingUtils.h ip/IpEndpointName.h ip/PacketListener.h ip/TimerListener.h
```

**Comment by sletz** [comment]
I guess this compiling on OS X:

/Applications/Xcode.app/Contents/Developer/usr/bin/make -C architecture/osclib
make -C oscpack
make -C faust
c++ -O3 -Wall -Wuninitialized -Wno-parentheses -I. -Iip -Iip/posix -Iosc -mmacosx-version-min=10.9   -c -o ip/IpEndpointName.o ip/IpEndpointName.cpp
c++ -O3 -Wall -Wuninitialized -Wno-parentheses -I. -Iip -Iip/posix -Iosc -mmacosx-version-min=10.9   -c -o ip/posix/NetworkingUtils.o ip/posix/NetworkingUtils.cpp
c++ -O3 -Wall -Wuninitialized -Wno-parentheses -I. -Iip -Iip/posix -Iosc -mmacosx-version-min=10.9   -c -o ip/posix/UdpSocket.o ip/posix/UdpSocket.cpp
c++ -O3 -Wall -Wuninitialized  -Wno-parentheses -I../oscpack -I../oscpack/osc -I. -Isrc -Isrc/lib -Isrc/msg -Isrc/nodes -Isrc/osc -Isrc/threads -I../.. -DINSTALL_PREFIX='""' -mmacosx-version-min=10.9     -c -o src/OSCControler.o src/OSCControler.cpp
c++ -O3 -Wall -Wuninitialized  -Wno-parentheses -I../oscpack -I../oscpack/osc -I. -Isrc -Isrc/lib -Isrc/msg -Isrc/nodes -Isrc/osc -Isrc/threads -I../.. -DINSTALL_PREFIX='""' -mmacosx-version-min=10.9     -c -o src/lib/OSCFError.o src/lib/OSCFError.cpp
c++ -O3 -Wall -Wuninitialized  -Wno-parentheses -I../oscpack -I../oscpack/osc -I. -Isrc -Isrc/lib -Isrc/msg -Isrc/nodes -Isrc/osc -Isrc/threads -I../.. -DINSTALL_PREFIX='""' -mmacosx-version-min=10.9     -c -o src/lib/OSCRegexp.o src/lib/OSCRegexp.cpp
c++ -O3 -Wall -Wuninitialized -Wno-parentheses -I. -Iip -Iip/posix -Iosc -mmacosx-version-min=10.9   -c -o osc/OscOutboundPacketStream.o osc/OscOutboundPacketStream.cpp
c++ -O3 -Wall -Wuninitialized  -Wno-parentheses -I../oscpack -I../oscpack/osc -I. -Isrc -Isrc/lib -Isrc/msg -Isrc/nodes -Isrc/osc -Isrc/threads -I../.. -DINSTALL_PREFIX='""' -mmacosx-version-min=10.9     -c -o src/msg/Message.o src/msg/Message.cpp
c++ -O3 -Wall -Wuninitialized -Wno-parentheses -I. -Iip -Iip/posix -Iosc -mmacosx-version-min=10.9   -c -o osc/OscPrintReceivedElements.o osc/OscPrintReceivedElements.cpp
c++ -O3 -Wall -Wuninitialized -Wno-parentheses -I. -Iip -Iip/posix -Iosc -mmacosx-version-min=10.9   -c -o osc/OscReceivedElements.o osc/OscReceivedElements.cpp
c++ -O3 -Wall -Wuninitialized  -Wno-parentheses -I../oscpack -I../oscpack/osc -I. -Isrc -Isrc/lib -Isrc/msg -Isrc/nodes -Isrc/osc -Isrc/threads -I../.. -DINSTALL_PREFIX='""' -mmacosx-version-min=10.9     -c -o src/nodes/FaustFactory.o src/nodes/FaustFactory.cpp
c++ -O3 -Wall -Wuninitialized -Wno-parentheses -I. -Iip -Iip/posix -Iosc -mmacosx-version-min=10.9   -c -o osc/OscTypes.o osc/OscTypes.cpp
rm -f liboscpack.a
ar cq liboscpack.a ip/IpEndpointName.o ip/posix/NetworkingUtils.o ip/posix/UdpSocket.o osc/OscOutboundPacketStream.o osc/OscPrintReceivedElements.o osc/OscReceivedElements.o osc/OscTypes.o
ranlib liboscpack.a
c++ -O3 -Wall -Wuninitialized  -Wno-parentheses -I../oscpack -I../oscpack/osc -I. -Isrc -Isrc/lib -Isrc/msg -Isrc/nodes -Isrc/osc -Isrc/threads -I../.. -DINSTALL_PREFIX='""' -mmacosx-version-min=10.9     -c -o src/nodes/FaustNode.o src/nodes/FaustNode.cpp
cp oscpack/liboscpack.a liboscpack.a
c++ -O3 -Wall -Wuninitialized  -Wno-parentheses -I../oscpack -I../oscpack/osc -I. -Isrc -Isrc/lib -Isrc/msg -Isrc/nodes -Isrc/osc -Isrc/threads -I../.. -DINSTALL_PREFIX='""' -mmacosx-version-min=10.9     -c -o src/nodes/MessageDriven.o src/nodes/MessageDriven.cpp
c++ -O3 -Wall -Wuninitialized  -Wno-parentheses -I../oscpack -I../oscpack/osc -I. -Isrc -Isrc/lib -Isrc/msg -Isrc/nodes -Isrc/osc -Isrc/threads -I../.. -DINSTALL_PREFIX='""' -mmacosx-version-min=10.9     -c -o src/nodes/RootNode.o src/nodes/RootNode.cpp
c++ -O3 -Wall -Wuninitialized  -Wno-parentheses -I../oscpack -I../oscpack/osc -I. -Isrc -Isrc/lib -Isrc/msg -Isrc/nodes -Isrc/osc -Isrc/threads -I../.. -DINSTALL_PREFIX='""' -mmacosx-version-min=10.9     -c -o src/osc/OSCAddress.o src/osc/OSCAddress.cpp
c++ -O3 -Wall -Wuninitialized  -Wno-parentheses -I../oscpack -I../oscpack/osc -I. -Isrc -Isrc/lib -Isrc/msg -Isrc/nodes -Isrc/osc -Isrc/threads -I../.. -DINSTALL_PREFIX='""' -mmacosx-version-min=10.9     -c -o src/osc/OSCIO.o src/osc/OSCIO.cpp
c++ -O3 -Wall -Wuninitialized  -Wno-parentheses -I../oscpack -I../oscpack/osc -I. -Isrc -Isrc/lib -Isrc/msg -Isrc/nodes -Isrc/osc -Isrc/threads -I../.. -DINSTALL_PREFIX='""' -mmacosx-version-min=10.9     -c -o src/osc/OSCListener.o src/osc/OSCListener.cpp
c++ -O3 -Wall -Wuninitialized  -Wno-parentheses -I../oscpack -I../oscpack/osc -I. -Isrc -Isrc/lib -Isrc/msg -Isrc/nodes -Isrc/osc -Isrc/threads -I../.. -DINSTALL_PREFIX='""' -mmacosx-version-min=10.9     -c -o src/osc/OSCSetup.o src/osc/OSCSetup.cpp
c++ -O3 -Wall -Wuninitialized  -Wno-parentheses -I../oscpack -I../oscpack/osc -I. -Isrc -Isrc/lib -Isrc/msg -Isrc/nodes -Isrc/osc -Isrc/threads -I../.. -DINSTALL_PREFIX='""' -mmacosx-version-min=10.9     -c -o src/osc/OSCStream.o src/osc/OSCStream.cpp
c++ -O3 -Wall -Wuninitialized  -Wno-parentheses -I../oscpack -I../oscpack/osc -I. -Isrc -Isrc/lib -Isrc/msg -Isrc/nodes -Isrc/osc -Isrc/threads -I../.. -DINSTALL_PREFIX='""' -mmacosx-version-min=10.9     -c -o src/threads/pthreads_impl.o src/threads/pthreads_impl.cpp
c++ -O3 -Wall -Wuninitialized  -Wno-parentheses -I../oscpack -I../oscpack/osc -I. -Isrc -Isrc/lib -Isrc/msg -Isrc/nodes -Isrc/osc -Isrc/threads -I../.. -DINSTALL_PREFIX='""' -mmacosx-version-min=10.9     -c -o src/threads/winthreads_impl.o src/threads/winthreads_impl.cpp
rm -f libOSCFaust.a
ar cq libOSCFaust.a src/OSCControler.o src/lib/OSCFError.o src/lib/OSCRegexp.o src/msg/Message.o src/nodes/FaustFactory.o src/nodes/FaustNode.o src/nodes/MessageDriven.o src/nodes/RootNode.o src/osc/OSCAddress.o src/osc/OSCIO.o src/osc/OSCListener.o src/osc/OSCSetup.o src/osc/OSCStream.o src/threads/pthreads_impl.o src/threads/winthreads_impl.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libOSCFaust.a(winthreads_impl.o) has no symbols
ranlib libOSCFaust.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libOSCFaust.a(winthreads_impl.o) has no symbols
cp faust/libOSCFaust.a libOSCFaust.a
libtool libOSCFaust.a liboscpack.a -o tmp.a && rm -f libOSCFaust.a && mv tmp.a libOSCFaust.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: libOSCFaust.a(winthreads_impl.o) has no symbols

**Comment by yurivict** [comment]
I do ```make all httpd```

**Comment by yurivict** [comment]
What is the top-level make target to use?
I use 'all' for w/out httpd, and 'all httpd' for w/httpd. Are these wrong targets?

**Comment by sletz** [comment]
make
make httpd
sudo make install

**Comment by yurivict** [comment]
I figured this out. It was a missing ifdef for FreeBSD in Nakefile.

Thanks!
